### ISSUE TITLE
netdata错误

### ISSUE THREAD

**Issue by jiawm** [sirpdboy/sirpdboy-package#18]
Applying ./patches/002-extra-patch-web_gui_index.html.patch using plaintext: 
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- a/web/gui/index.html
|+++ b/web/gui/index.html
--------------------------
No file to patch.  Skipping patch.
3 out of 3 hunks ignored
Patch failed!  Please fix ./patches/002-extra-patch-web_gui_index.html.patch!
Makefile:98: recipe for target '/workdir/openwrt/build_dir/target-x86_64_musl/netdata-1.31.0/.prepared_15bc783120bce09d9b4904f03fcedee0_6664517399ebbbc92a37c5bb081b5c53' failed
make[3]: *** [/workdir/openwrt/build_dir/target-x86_64_musl/netdata-1.31.0/.prepared_15bc783120bce09d9b4904f03fcedee0_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[3]: Leaving directory '/workdir/openwrt/package/sirpdboy/netdata'
time: package/sirpdboy/netdata/compile#0.48#0.23#0.58
package/Makefile:111: recipe for target 'package/sirpdboy/netdata/compile' failed
make[2]: *** [package/sirpdboy/netdata/compile] Error 2
make[1]: *** [/workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2

**Comment by sirpdboy** [comment]
新版本已经解决
