### ISSUE TITLE
feeds 报错！

### ISSUE THREAD

**Issue by rabbired** [sirpdboy/sirpdboy-package#26]
fatal: No url found for submodule path 'luci-app-poweroffdevice' in .gitmodules
failed.
ERROR: please fix feeds/opentopd/luci-app-access-control/Makefile - see logs/feeds/opentopd/luci-app-access-control/dump.txt for details
ERROR: please fix feeds/opentopd/speedtest-cli/Makefile - see logs/feeds/opentopd/speedtest-cli/dump.txt for details

**Comment by madman43** [comment]
我是报netspeedtest的错误

**Comment by sirpdboy** [comment]
已经修复了。
