### ISSUE TITLE
luci-app-koolproxyR/ 今天变了一个固件，发现有几个文件权限错误。请抽空修正。

### ISSUE THREAD

**Issue by jikkyfu** [sirpdboy/sirpdboy-package#33]
/usr/share/koolproxy/kpupdate
/usr/share/koolproxy/camanagement
/etc/init.d/koolproxy

如果跟我一样发现无法启动的，无法更新的，请将上述几个文件的权限修改 chmod +x

**Comment by sirpdboy** [comment]
好的。 正常是自己加上权限了
