### ISSUE TITLE
虚心学习。您是如何修改/usr/lib/lua/luci/view  的网络监控usage页面的

### ISSUE THREAD

**Issue by jk2008chd** [sirpdboy/sirpdboy-package#34]
您好，sirpdboy。大佬，我非常喜欢您的固件，也在用您的插件库编译，但是有美中不足的地方我尝试学习了好多天不得其解。遂来叨扰。
您固件中宽带监控使用率项我页面非常好看。我非常想在自己编译的对话中加入。苦思不得解，在/usr/lib/lua/luci/view 找到了该网页页面，但是如何不知道替换与使用。

ps 如果您的固件加入网易云 vssr 和VPN softenter，我就可以放弃折腾啦 哈哈哈哈。

**Comment by sirpdboy** [comment]
大全版 就有这些的哦。

**Comment by jk2008chd** [comment]
![image](https://user-images.githubusercontent.com/69377458/161453730-b05d780e-27e6-4149-97b3-0a95c5a53cf6.png)
Hi， sirpdboy · 研究了一段时间后来还是发现这个页面很好 但是数据差的离谱，统计流量结果是不真实的。我已经搞不明白是因为什么原因了。
cgi-bin/luci/admin/nlbw/usage 页面显示流量数据几乎为0
PS ： /cgi-bin/luci/admin/nlbw/onliner/speed 与cgi-bin/luci/admin/nlbw/display 这两个页面的数据还算正常

**Comment by jk2008chd** [comment]
这好像和我的推送微信pushbot里显示的设备流量统计一样奇怪， 都是不正常的。
