### ISSUE TITLE
使用LEDE的源码和您的package包。 安装网络测速netspeedtest ，编译后在openwrt中无法正确开启服务。

### ISSUE THREAD

**Issue by jk2008chd** [sirpdboy/sirpdboy-package#35]
iperf3 服务端已停止
iperf3 服务启动    执行操作

点执行操作后 瞬间提示执行完成。实际没有效果
正在收集数据...
操作执行完毕

**Comment by jk2008chd** [comment]
已解决。
如果是自己编译的话  要在make menuconfig中 network选用iperf3.作为基础

**Comment by jk2008chd** [comment]
8.外网测速使用speedtest.net测速内核，需要依赖speedtest,另外感谢superspeed和user1121114685因为借用了你们的灵感！

请教 说明里的依赖speedtest 怎么找到它

**Comment by sirpdboy** [comment]
speedtest 官网下载。目前好像没提供了。。

**Comment by sirpdboy** [comment]
@jk2008chd   只是因为看了他们有这个测试速度的一个SH脚本。实际上我这代码和他们代码没有一点关系。。可以用名字直接访问他们的仓库。

**Comment by bonnyandsky** [comment]
> speedtest 官网下载。目前好像没提供了。。

就是说外网的测速功能用不了了？

**Comment by sirpdboy** [comment]
可以用
