### ISSUE TITLE
安装wrtbwmon后，其他以及默认主题下 界面显示不健全。

### ISSUE THREAD

**Issue by jk2008chd** [sirpdboy/sirpdboy-package#36]
安装wrtbwmon后，其他以及默认主题下 界面显示不健全。
页面为http://192.168.123.126/cgi-bin/luci/admin/nlbw/usage

**Comment by sirpdboy** [comment]
主题原因。。

**Comment by bonnyandsky** [comment]
> 主题原因。。
那个主题可以显示正常

**Comment by jk2008chd** [comment]
确实，我一个一个的试 试了一夜，也发现了是主题原因了
