### ISSUE TITLE
20210301版本PPTP无法使用

### ISSUE THREAD

**Issue by 938134** [sirpdboy/sirpdboy-package#4]
Sat Mar  6 18:29:42 2021 daemon.notice netifd: Interface 'gk' is setting up now
Sat Mar  6 18:29:44 2021 daemon.err pppd[13324]: Error loading shared library /usr/lib/pppd/2.4.8/p p t p.so: No such file or directory
Sat Mar  6 18:29:44 2021 daemon.err pppd[13324]: Couldn't load plugin p p t p.so
Sat Mar  6 18:29:44 2021 daemon.notice netifd: gk (13324): /usr/sbin/pppd: Error loading shared library /usr/lib/pppd/2.4.8/p p t p.so: No such file or directory
Sat Mar  6 18:29:44 2021 daemon.notice netifd: gk (13324): /usr/sbin/pppd: Couldn't load plugin p p t p.so
Sat Mar  6 18:29:44 2021 daemon.notice netifd: Interface 'gk' is now down

安装ppp-mod-pptp时新建了2.4.9目录，pptp.so文件在2.4.9下。这个能修正吗

**Comment by sirpdboy** [comment]
这个是版本目录不配套，ppp-mod-pptp 安装2.4。8的 。或者 将2.4.9改名为 2.4.8 。

**Comment by 938134** [comment]
改了也不行。说两者版本不匹配&nbsp;



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "SirPdboy"<notifications@github.com&gt;; 
发送时间: 2021年3月7日(星期天) 中午11:13
收件人: "sirpdboy/sirpdboy-package"<sirpdboy-package@noreply.github.com&gt;; 
抄送: "938134"<938134@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [sirpdboy/sirpdboy-package] 20210301版本PPTP无法使用 (#4)





 
这个是版本目录不配套，ppp-mod-pptp 安装2.4。8的 。或者 将2.4.9改名为 2.4.8 。
