### ISSUE TITLE
luci-app-netspeedtest 报错

### ISSUE THREAD

**Issue by retusus** [sirpdboy/sirpdboy-package#45]
make[3]: Leaving directory '/home/orange/lede/feeds/packages/net/iperf3'
time: package/feeds/packages/iperf3/nossl/compile#0.13#0.01#0.12
make[3]: Entering directory '/home/orange/lede/feeds/opentopd/luci-app-netspeedtest'
Makefile:47: *** DESCRIPTION:= is obsolete, use Package/PKG_NAME/description.  Stop.
make[3]: Leaving directory '/home/orange/lede/feeds/opentopd/luci-app-netspeedtest'
time: package/feeds/opentopd/luci-app-netspeedtest/compile#0.06#0.02#0.07
    ERROR: package/feeds/opentopd/luci-app-netspeedtest failed to build.
make[2]: *** [package/Makefile:116: package/feeds/opentopd/luci-app-netspeedtest/compile] Error 1
make[2]: Leaving directory '/home/orange/lede'
make[1]: *** [package/Makefile:110: /home/orange/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/orange/lede'
make: *** [/home/orange/lede/include/toplevel.mk:230：world] 错误 2

**Comment by sirpdboy** [comment]
问题已经修复，
