### ISSUE TITLE
passwall内设置geoip即断网，缺失geoip.dat如何修复？

### ISSUE THREAD

**Issue by kagurareina** [sirpdboy/sirpdboy-package#48]
使用 OpenWrt Ipv4P S2021.01.14 by Sirpdboy

检查了
/usr/share/xray/ （目录不存在）
/usr/share/passwall/rules
都不存在geosite.dat和geoip.dat

passwall内【组件更新】已是最新。【规则管理】内没有geoip选项，只有gfwlist 、chnroute、chnroute6。
这算谁的错？passwall没加geoip.dat？xray-core没加geoip.dat？如何修复？

**Comment by sirpdboy** [comment]
规则管理  选择这二个，再点更新就可以了。
