### ISSUE TITLE
仓库在使用时出现一些问题

### ISSUE THREAD

**Issue by WindyMadman** [sirpdboy/sirpdboy-package#50]
luci-app-socat 依赖于 socat 但是 socat编译出来的文件会跟luci-app-socat自带的内置文件冲突

Collected errors:
 * check_data_file_clashes: Package luci-app-socat wants to install file /home/windy/lede/build_dir/target-x86_64_musl/root-x86/etc/config/socat
        But that file is already provided by package  * socat
 * check_data_file_clashes: Package luci-app-socat wants to install file /home/windy/lede/build_dir/target-x86_64_musl/root-x86/etc/init.d/socat
        But that file is already provided by package  * socat
 * opkg_install_cmd: Cannot install package luci-app-socat.
 * check_data_file_clashes: Package luci-app-socat wants to install file /home/windy/lede/build_dir/target-x86_64_musl/root-x86/etc/config/socat
        But that file is already provided by package  * socat
 * check_data_file_clashes: Package luci-app-socat wants to install file /home/windy/lede/build_dir/target-x86_64_musl/root-x86/etc/init.d/socat
        But that file is already provided by package  * socat
 * opkg_install_cmd: Cannot install package luci-i18n-socat-zh-cn.
package/Makefile:66: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 255
make[2]: Leaving directory '/home/windy/lede'
package/Makefile:111: recipe for target '/home/windy/lede/staging_dir/target-x86_64_musl/stamp/.package_install' failed
make[1]: *** [/home/windy/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/windy/lede'
Build failed - please re-run with -j1 to see the real error message
/home/windy/lede/include/toplevel.mk:228: recipe for target 'world' failed
make: *** [world] Error 1

**Comment by sirpdboy** [comment]
好的。原来socat比较老。。现在可以移除了。
