### ISSUE TITLE
能否加上bcm5719的驱动

### ISSUE THREAD

**Issue by laobanbiefangcu** [sirpdboy/sirpdboy-package#54]
大佬，4月1号的固件不识别bcm5719网卡了，能否加上。3月份的能识别出来，正常使用

**Comment by sirpdboy** [comment]
6.1号的版本将会支持。

**Comment by winneis** [comment]
我现在用的是这个无线网卡加openwrtQualcomm Atheros QCA9880 802.11nac (radio0)

也无法使用。测试过5个版本。12月9号以后的 ROm 都不能用。
