### ISSUE TITLE
luci-app-socat

### ISSUE THREAD

**Issue by a7502** [sirpdboy/sirpdboy-package#56]
lede源码，选中这个luci-app-socat就不能编译成功，不选择才可以编译成功。大佬修复下。。。

Collected errors:
 * check_data_file_clashes: Package luci-app-socat wants to install file /home/koko/lede/build_dir/target-x86_64_musl/root-x86/etc/config/socat
        But that file is already provided by package  * socat
 * check_data_file_clashes: Package luci-app-socat wants to install file /home/koko/lede/build_dir/target-x86_64_musl/root-x86/etc/init.d/socat
        But that file is already provided by package  * socat
 * opkg_install_cmd: Cannot install package luci-app-socat.
 * check_data_file_clashes: Package luci-app-socat wants to install file /home/koko/lede/build_dir/target-x86_64_musl/root-x86/etc/config/socat
        But that file is already provided by package  * socat
 * check_data_file_clashes: Package luci-app-socat wants to install file /home/koko/lede/build_dir/target-x86_64_musl/root-x86/etc/init.d/socat
        But that file is already provided by package  * socat
 * opkg_install_cmd: Cannot install package luci-i18n-socat-zh-cn.
make[2]: *** [package/Makefile:70: package/install] Error 255

**Comment by sirpdboy** [comment]
你这个是少了 socat的依赖。

**Comment by sirpdboy** [comment]
socat 这个依赖
