### ISSUE TITLE
luci-app-poweroffdevice 错误

### ISSUE THREAD

**Issue by geminijummnm** [sirpdboy/sirpdboy-package#57]
luci-app-poweroffdevice组件在源代码中有，但是连接错误导致，github action报错
Updating feed 'siropboy' from 'https://github.com/siropboy/sirpdboy-package' ...
Cloning into './feeds/siropboy'...
fatal: No url found for submodule path 'luci-app-poweroffdevice' in .gitmodules
failed.
希望sirpdboy修复一下

**Comment by jakaz1280** [comment]
luci-app-poweroffdevice子模块url不对，一种可行的解决方案是fork后修改url或者干脆删掉这个子模块，这样脚本能正常执行
