### ISSUE TITLE
关于被聊天群退出的申诉

### ISSUE THREAD

**Issue by sniper3209** [sirpdboy/sirpdboy-package#60]
加入聊天群近二年了，昨天就因为一句：7/1 版固件仍存在CPU负载100%BUG，请大家观望 被踢了。
现在是怎么了？有些BUG是在特定状态下出现的，还不一定复现，使用者第一时间当然是想着去如何解决，怎会想着如何举证？
日志对CPU100%的bug也没有相关记录的，之前版本就有过这BUG。对于要求使用者规范反馈行为没有错，但不能说你没有遇到BUG就能证明没有BUG，更加不能如此蛮横，说一句话就踢人，还专门出公告，搞到我好像是破坏分子一样，请问管理者是什么心态？
对于固件的作者，我也是尊重其劳动成果的，也是捐了款的，为什么现在变成这样了？有问题还说不得了？我反正是心态崩了，好心提醒却遭此待遇。
在此，我本人对聊天群管理者表示严重抗议！

**Comment by sirpdboy** [comment]
好吧。有问题 就提供 问题的具体故障和截图。。否则会误导别人。至于 不是故意 攻击和抹黑的可以取消。

**Comment by sirpdboy** [comment]
你的TG名字 提供一下。。 可以帮你取消。

**Comment by sniper3209** [comment]
>TG ID ----  sniper1121

**Comment by sniper3209** [comment]
非常感谢您，我的id  sniper1121

SirPdboy ***@***.***> 于 2022年9月23日周五 22:04写道：
