### ISSUE TITLE
希望增加kms server 和 mosdns

### ISSUE THREAD

**Issue by jinwyp** [sirpdboy/sirpdboy-package#62]
希望增加kms server 和 mosdns  这两个精简包希望加上 
有了mosdns 其他的其实都可以删掉了 例如smartdns等

还有希望ssrplus能用原版的 而不是ssrplus++

**Comment by sirpdboy** [comment]
原版和这个 一样的。。这个只是多了界面上的测试 。。其它完全 一样。。

**Comment by jinwyp** [comment]
ssrplus++ 比原版差很多, 慢很多,而且核心用的v2ray , 不支持vless xtls
