### ISSUE TITLE
luci-app-adguardhome插件能不能新建个独立仓库同步维护

### ISSUE THREAD

**Issue by threerog** [sirpdboy/sirpdboy-package#70]
luci-app-adguardhome插件能不能新建个独立仓库同步维护
目前github上好像只能您还在维护luci-app-adguardhome插件
但是我只需要这一个插件源而不是整个package软件源，避免插件冲突

**Comment by threerog** [comment]
另外netdata好像无法启用

**Comment by sirpdboy** [comment]
太多插件了，只能维护一个是一个。。 这个不是我原创。。不太好弄独立仓库。
