### ISSUE TITLE
luci-app-eqosplus在IPQ6018,4.4内核上运行无效并报错

### ISSUE THREAD

**Issue by jitj2021** [sirpdboy/sirpdboy-package#74]
luci-app-eqosplus在IPQ6018,4.4.60内核上运行，限速（设置为0.1）无效，报错日志如下：
Sun Feb 18 22:37:50 2024 daemon.err insmod: module is already loaded - sch_htb
Sun Feb 18 22:38:15 2024 daemon.info procd: Instance eqosplus::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
Sun Feb 18 22:38:34 2024 daemon.err insmod: module is already loaded - sch_htb
Sun Feb 18 22:38:34 2024 daemon.info procd: Instance eqosplus::instance1 s in a crash loop 7 crashes, 0 seconds since last crash
Sun Feb 18 22:40:51 2024 daemon.notice ttyd[8243]: rops_handle_POLLIN_netlink: DELADDR
Sun Feb 18 22:40:51 2024 daemon.err insmod: module is already loaded - sch_htb
Sun Feb 18 22:40:51 2024 daemon.info procd: Instance eqosplus::instance1 s in a crash loop 8 crashes, 0 seconds since last crash
Sun Feb 18 22:42:53 2024 daemon.notice ttyd[8243]: rops_handle_POLLIN_netlink: DELADDR
Sun Feb 18 22:42:54 2024 daemon.err insmod: module is already loaded - sch_htb
Sun Feb 18 22:42:54 2024 daemon.info procd: Instance eqosplus::instance1 s in a crash loop 9 crashes, 0 seconds since last crash
Sun Feb 18 22:43:29 2024 daemon.notice ttyd[8243]: rops_handle_POLLIN_netlink: DELADDR
Sun Feb 18 22:44:02 2024 daemon.err insmod: module is already loaded - sch_htb
Sun Feb 18 22:44:27 2024 daemon.info procd: Instance eqosplus::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
Sun Feb 18 22:45:29 2024 daemon.err uhttpd[6349]: sh: write error: Broken pipe

**Comment by sirpdboy** [comment]
冲突导致。。
