### ISSUE TITLE
如果我想编译其他CPU版本怎么编译？

### ISSUE THREAD

**Issue by JackJie-J** [sirpdboy/sirpdboy-package#9]
我想在你的基础上编译其他机型版本，比如R2S，怎么编译呢？
是在LEAN大佬的源码上去掉其他仓库之加入你的仓库吗？这样好像不行
如果不能，能加入其他机型吗？

**Comment by sirpdboy** [comment]
时间有限，主要是没机器测试 。。所以不提供这个了。
